require_relative '../../app/helpers/env_helper'                                 # requires so that path is still valid if engine is used in other project

# create secrets for encryption

secrets_file = File.join(Rails.root, 'config', 'secrets.yml')
rails_env = ENV['RAILS_ENV'] || 'production'
content = "
# File generated by config/initializers/create_secrets.rb for compatibility reason only
# This file will be overwritten with the current secret_key_base each time Panorama starts

#{rails_env}:
    secret_key_base: \"#{EnvHelper.secret_key_base}\"
"
begin
  File.write(secrets_file, content)
rescue Exception => e
  puts "Error creating secrets file '#{secrets_file}'\n#{e.class}: #{e.message}"
end

