# encoding: utf-8
module DbaPgaHelper

  # columns in v$pgastat already known how to interpret them
  def known_pga_stat_columns
    million = (1024*1024).to_f

    {
      "aggregate PGA target parameter"        => {caption: "aggregate PGA target parameter (MB)",       scale: 2, divisor: million, title: "Current value of the PGA_AGGREGATE_TARGET initialization parameter. If this parameter is not set, then its value is 0 and automatic management of PGA memory is disabled."},
      "aggregate PGA auto target"             => {caption: "aggregate PGA auto target (MB)",            scale: 2, divisor: million, title: "Amount of PGA memory the Oracle Database can use for work areas running in automatic mode. This amount is dynamically derived from the value of the PGA_AGGREGATE_TARGET initialization parameter and the current work area workload, and continuously adjusted by the Oracle Database. If this value is small compared to the value of PGA_AGGREGATE_TARGET, then a large amount of PGA memory is used by other components of the system (for example, PL/SQL or Java memory) and little is left for work areas. The DBA must ensure that enough PGA memory is left for work areas running in automatic mode."},
      "global memory bound"                   => {caption: "global memory bound (MB)",                  scale: 2, divisor: million, title: "Maximum size of a work area executed in automatic mode. This value is continuously adjusted by the Oracle Database to reflect the current state of the work area workload. The global memory bound generally decreases when the number of active work areas is increasing in the system. If the value of the global bound decreases below 1 MB, then the value of PGA_AGGREGATE_TARGET should be increased."},
      "total PGA inuse"                       => {caption: "total PGA in use (MB)",                     scale: 2, divisor: million, title: "Indicates how much PGA memory is currently consumed by work areas. This number can be used to determine how much memory is consumed by other consumers of the PGA memory (for example, PL/SQL or Java)."},
      "total PGA allocated"                   => {caption: "total PGA allocated (MB)",                  scale: 2, divisor: million, title: "Current amount of PGA memory allocated by the instance. The Oracle Database attempts to keep this number below the value of the PGA_AGGREGATE_TARGET initialization parameter. However, it is possible for the PGA allocated to exceed that value by a small percentage and for a short period of time when the work area workload is increasing very rapidly or when PGA_AGGREGATE_TARGET is set to a small value."},
      "maximum PGA allocated"                 => {caption: "maximum PGA allocated (MB)",                scale: 2, divisor: million, title: "Maximum number of bytes of PGA memory allocated at one time since instance startup."},
      "total PGA used"                        => {caption: "total PGA used (MB)",                       scale: 2, divisor: million, title: "Indicates how much PGA memory is currently consumed by work areas. This number can be used to determine how much memory is consumed by other consumers of the PGA memory (for example, PL/SQL or Java)."},
      "total PGA used for auto workareas"     => {caption: "total PGA used for auto workareas (MB)",    scale: 2, divisor: million, title: "Indicates how much PGA memory is currently consumed by work areas running under the automatic memory management mode. This number can be used to determine how much memory is consumed by other consumers of the PGA memory (for example, PL/SQL or Java)."},
      "maximum PGA used for auto workareas"   => {caption: "maximum PGA used for auto workareas (MB)",  scale: 2, divisor: million, title: "Maximum amount of PGA memory consumed at one time by work areas running under the automatic memory management mode since instance startup."},
      "total PGA used for manual workareas"   => {caption: "total PGA used for manual workareas (MB)",  scale: 2, divisor: million, title: "Indicates how much PGA memory is currently consumed by work areas running under the manual memory management mode. This number can be used to determine how much memory is consumed by other consumers of the PGA memory (for example, PL/SQL or Java)."},
      "maximum PGA used for manual workareas" => {caption: "maximum PGA used for manual workareas (MB)",scale: 2, divisor: million, title: "Maximum amount of PGA memory consumed at one time by work areas running under the manual memory management mode since instance startup."},
      "MGA allocated (under PGA)"             => {caption: "MGA allocated (under PGA) (MB)",            scale: 2, divisor: million, title: "Amount of memory allocated as shared memory in MGA (managed global area)"},
      "maximum MGA allocated"                 => {caption: "maximum MGA allocated (MB)",                scale: 2, divisor: million, title: "Maximum amount of memory allocated as shared memory in MGA (managed global area)"},
      "over allocation count"                 => {caption: "over allocation count",                     scale: 0, divisor: 1,       title: "This statistic is cumulative since instance startup. Over allocating PGA memory can happen if the value of PGA_AGGREGATE_TARGET is too small. When this happens, the Oracle Database cannot honor the value of PGA_AGGREGATE_TARGET and extra PGA memory needs to be allocated. If over allocation occurs, then increase the value of PGA_AGGREGATE_TARGET using the information provided by the V$PGA_TARGET_ADVICE view."},
      "bytes processed"                       => {caption: "MBytes processed",                          scale: 2, divisor: million, title: "Number of MBytes processed by memory intensive SQL operators."},
      "extra bytes read/written"              => {caption: "extra MBytes read/written",                 scale: 2, divisor: million, title: "Number of MBytes processed during extra passes of the input data. When a work area cannot run optimal, one or more of these extra passes is performed."},
      "cache hit percentage"                  => {caption: "cache hit percentage",                      scale: 2, divisor: 1,       title: "A metric computed by the Oracle Database to reflect the performance of the PGA memory component, cumulative since instance startup. A value of 100% means that all work areas executed by the system since instance startup have used an optimal amount of PGA memory. When a work area cannot run optimal, one or more extra passes is performed over the input data. This will reduce the cache hit percentage in proportion to the size of the input data and the number of extra passes performed."},
      "total freeable PGA memory"             => {caption: "total freeable PGA memory (MB)",            scale: 2, divisor: million, title: "Number of MBytes of PGA memory in all processes that could be freed back to the operating system."},
      "PGA memory freed back to OS"           => {caption: "PGA memory freed back to OS (MB)",          scale: 2, divisor: million, title: "Number of MBytes of PGA memory freed back to the operating system."},
      "recompute count (total)"               => {caption: "recompute count",                           scale: 0, divisor: 1,       title: "Number of times the instance bound, which is a cap on the maximum size of each active work area, has been recomputed. Generally, the instance bound is recomputed in the background every 3 seconds, but it could be recomputed by a foreground process when the number of work areas changes rapidly in a short period of time."},
      "process count"                         => {caption: "process count",                             scale: 0, divisor: 1,       title: "Number of processes active within up to the last 3 seconds."},
      "max processes count"                   => {caption: "max processes count",                       scale: 0, divisor: 1,       title: "Maximum number of processes active at any one time since instance startup."},
      "Used_SQL"                              => {caption: "PGA used for SQL (MB)",                     scale: 2, divisor: million, title: "Used memory for category \"SQL\".\nSelected from DBA_Hist_Process_Mem_Summary"},
      "Alloc_SQL"                             => {caption: "PGA allocated for SQL (MB)",                scale: 2, divisor: million, title: "Allocated memory for category \"SQL\".\nSelected from DBA_Hist_Process_Mem_Summary"},
      "Used_PL/SQL"                           => {caption: "PGA used for PL/SQL (MB)",                  scale: 2, divisor: million, title: "Used memory for category \"PL/SQL\".\nSelected from DBA_Hist_Process_Mem_Summary"},
      "Alloc_PL/SQL"                          => {caption: "PGA allocated for PL/SQL (MB)",             scale: 2, divisor: million, title: "Allocated memory for category \"PL/SQL\".\nSelected from DBA_Hist_Process_Mem_Summary"},
      "Used_Other"                            => {caption: "PGA used for Other (MB)",                   scale: 2, divisor: million, title: "Used memory for category \"Other\".\nSelected from DBA_Hist_Process_Mem_Summary"},
      "Alloc_Other"                           => {caption: "PGA allocated for Other (MB)",              scale: 2, divisor: million, title: "Allocated memory for category \"Other\".\nSelected from DBA_Hist_Process_Mem_Summary"},
      "Used_Freeable"                         => {caption: "PGA used freeable (MB)",                    scale: 2, divisor: million, title: "Used memory for category \"Freeable\".\nSelected from DBA_Hist_Process_Mem_Summary"},
      "Alloc_Freeable"                        => {caption: "PGA allocated freeable (MB)",               scale: 2, divisor: million, title: "Allocated memory for category \"Freeable\".\nSelected from DBA_Hist_Process_Mem_Summary"},
    }
  end

end